### ISSUE TITLE
Add repository

### ISSUE THREAD

**Issue by delgross** [RobertD502/home-assistant-whistle#11]
Admittedly a new user.  Any idea why the depository URL is invalid in HA
[
https://github.com/RobertD502/home-assistant-whistle

**Comment by RobertD502** [comment]
I'm assuming you're trying to add the repository from the "Add-On" section of Home Assistant, which this isn't (Common mistake as a new user so no worries!).

This repository needs to be added in HACS (Home Assistant Community Store).

**Comment by RobertD502** [comment]
I'm assuming you're trying to add the repository from the "Add-On" section of Home Assistant, which this isn't (Common mistake as a new user so no worries!).

This repository needs to be added in HACS (Home Assistant Community Store).

**Comment by delgross** [comment]
Got it. Sorry to waste your time. My dog Amigo and I thank you.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by RobertD502** [comment]
Not a problem at all! Sorry I missed the Github notification and didn't get to it until today.
