### ISSUE TITLE
Feature Request: Wellness Score

### ISSUE THREAD

**Issue by jak119** [RobertD502/home-assistant-whistle#12]
Given that the API is not official, I'm not sure if this is even available but if possible I'd love to see the "wellness score" and health metrics available in Home Assistant. 

Even without that, love the integration, thanks for taking the time to write it!

**Comment by RobertD502** [comment]
I'll take a look into it. Off the bat, I know the wellness index is returned at `/api/pets/pet_number/dashboard/wellness_index`.

**Comment by RobertD502** [comment]
And the health metrics can be pulled from `/api/pets/pet_number/health/trends`.

I'll have to update the backend library (whistleaio) to account for these endpoints and then update the integration to create the entities for each one of these.

**Comment by RobertD502** [comment]
I'm thinking a sensor for each one of the health metrics listing out the word score (okay, below average, etc) and then attribute(s) that list out the actual number- for example, the sleeping metric has both sleeping duration (in seconds) and # of sleep disruptions.

**Comment by jak119** [comment]
Thanks for considering this! 

> I'm thinking a sensor for each one of the health metrics listing out the word score (okay, below average, etc) and then attribute(s) that list out the actual number- for example, the sleeping metric has both sleeping duration (in seconds) and # of sleep disruptions.

That seems like a reasonable approach to me. I already have a dog dashboard to track / coordinate feeding and remind me to walk him if I have been bad about it that day so I can see myself adding an entity card to show these at a glance.

**Comment by RobertD502** [comment]
> The new sensors look / work great. Thanks so much for adding them! 

No problem at all!
