### ISSUE TITLE
Issue in "Battery days left" Display

### ISSUE THREAD

**Issue by BigThunderSR** [RobertD502/home-assistant-whistle#15]
The "Battery days left" sensor shows the output in hours instead of the expected unit of days, but the graph shows the output in days as expected:

![image](https://github.com/RobertD502/home-assistant-whistle/assets/17056173/79a9b83f-c447-424e-a752-c1b9b8199f13)

In this case, 223 Hrs and 12 Min is approximately 9.3 days

Also, thanks for your work on this integration!

**Comment by RobertD502** [comment]
Hi, there is nothing I can do to change this. That is just how Home Assistant decides to present it in the UI. The sensor does in fact have a unit of measurement of days (which is why the graph is correct). The reason for showing hours for the sensor is a design decision by Home Assistant itself.

**Comment by RobertD502** [comment]
![image](https://github.com/RobertD502/home-assistant-whistle/assets/52541649/e3590cf6-660a-41f0-a5fc-b8795de4f81b)

As you can see, the sensor itself has a state in days and not hours like the UI shows.
