### ISSUE TITLE
Metric Conversions

### ISSUE THREAD

**Issue by CayCanSafety** [RobertD502/home-assistant-whistle#17]
Hey, 

First off, this integration is amazing. Thanks for all the hard work. One minor thing... would it be possible to add a setting/config/etc. to convert the distances in Miles to Kilometres for us metric folks?

Thanks

**Comment by RobertD502** [comment]
Just released `0.1.10`. Update to it and you will be able to change the units - In the Home Assistant UI, click on the distance sensor (you'll need to do this for both the Distance and Event distance sensors), click on the gear icon in the upper right-hand corner and there you'll be able to select your unit of measurement (km)!

**Comment by CayCanSafety** [comment]
Sir, you're setting the bar too high. Incredible. Thank you.
