### ISSUE TITLE
"Home" Location Config Option

### ISSUE THREAD

**Issue by swamplynx** [RobertD502/home-assistant-whistle#3]
Thanks so much for developing this. I'm in the process of my SmartThings divorce where I wrote a custom app to pull in Whistle location info for pet presence. I'm still learning the ins out outs of HA, so there may be a better way of doing this, but so that the device tracker better integrates with HA's Person function, would it be possible to...

1) Set a "home" location in the integration config, so that when the pet is at this location the device tracker state is 'home' for the Person function. The reason I can't just name my house 'home' in the Whistle app, is I have two homes with two HA instances.
2) When the pet is outside of any define safe place, would it make more sense to set the device tracker state to 'not_home' vs 'Away'? I believe not_home is the away attribute the Person function expects to set away status.
3) How often does the integration poll the Whistle servers? Could a configuration option be made for this?

Thank you!!!

**Comment by RobertD502** [comment]
1. The device tracker place name is used for the state the way it currently is. I'm trying to keep it as native to the whistle as possible. 

If you want to use different locations:
- Use a person in Home Assistant
- Create Zones within Home Assistant
- Comment out lines 137-148 in device_tracker.py

2. If you comment out the lines as stated above, the state for the "person" associated with the device tracker entity when outside of a zone will depend on Home Assistant.

3. The integration polls Whistle's servers every 2 minutes. If you want to change this: line 14 of device_tracker.py change scan interval to your desired number of seconds.

**Comment by RobertD502** [comment]
@swamplynx I just pushed out version `0.1.2` which allows you to select if you want to use zones you created within the Whistle app or zones you created within Home Assistant. To select which to use, from the Home Assistant integrations page, select configure and then pick an option:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/52541649/190012105-f40bbda5-7ce3-405d-ac05-6348e736a047.png">
<img width="393" alt="image" src="https://user-images.githubusercontent.com/52541649/190012196-8db749df-9d37-40d4-934f-b7279e9b06f1.png">

**Comment by swamplynx** [comment]
Awesome. Thanks! I already forked your latest to accommodate my HA zones, but it is sloppy and hard coded. I’ll give this a whirl. I also made one other change you might want to adopt and switched from the str to float function for lat / lon. I needed this to get the HA proximity integration to work.

**Comment by RobertD502** [comment]
If you're running a version below 0.1.0 right now, be sure to read the 0.1.0 release notes before updating to 0.1.2. As of 0.1.0, the integration was completely rewritten and uses a new backend. Everything is broken out into sensors now instead of attributes.

Regarding lat and long being set as str: this is fixed in version 0.1.2 and returns the original float. For some reason the Home Assistant dev docs are wrong and list the type as a string instead of float for lat and long, which resulted in me converting the original floats to strings. I have a PR open right now with them to make that change to their documentation.
