### ISSUE TITLE
Failed to update data for device 'whistle_XXXX' from Whistle servers

### ISSUE THREAD

**Issue by swamplynx** [RobertD502/home-assistant-whistle#5]
Every few hours I get a "Failed to update data for device 'XXXX' from Whistle servers." (I haven't had the chance to change the logger level to see the actual HTTP error). While not a big deal and occasional connectivity hiccups are not unexpected, the issue is that when this occurs it causes the state of the device tracker entity to flip to "unknown" and then flip back to the location the next time the integration is able to pull an update. Is there a more graceful way to handle connectivity issues, e.g. wait and retry, before updating the state?

**Comment by RobertD502** [comment]
The whistle servers have been acting up recently, however this is the correct behavior when fetching data fails. If fetching the data fails then, in reality, the real location is unknown. Setting the location manually or keeping the old location would not be accurate. The entity sends a request to Whistle's servers every 30 seconds, so the update is retried whenever it fails. The other option is to mark the entire entity as unavailable if fetching data fails.
