### ISSUE TITLE
Standard possible?

### ISSUE THREAD

**Issue by danb5** [RobertD502/home-assistant-whistle#6]
This is fantastic.  What would it take to get this added as a Standard Home Assistant Integration?

**Comment by RobertD502** [comment]
At this time I have no plans of attempting to move it officially into HA. It would require a decent amount of extra work and time that I don't have at this moment. Maintaining control of the app and distributing it through HACS also means I can push out updates whenever needed without having to wait for HA to release a new update for changes to reach end users.
